---
- name: Include AWS vars
  include_vars:
    file: "{{ playbook_dir }}/../vars/aws_vars.yml"

- name: Provision EC2 instance
  ec2_instance:
    key_name: "{{ aws_key_name }}"
    instance_type: "{{ aws_instance_type }}"
    image_id: "{{ aws_ami_id }}"
    wait: true
    region: "{{ aws_region }}"
    vpc_subnet_id: "{{ aws_subnet_id }}"
    security_groups:
      - "{{ aws_security_group }}"
  register: ec2

    #- name: Add EC2 instance to host group
    #add_host:
    #name: "{{ item.public_ip }}"
    #groups: web_servers
    #with_items: "{{ ec2.instances }}"

